name: tao-train-action-recognition
network_arch: action_recognition
automl_enabled: true
container_image: tao_toolkit.pyt
data_format: default
gpu_spec_key: train.num_gpus
actions:
  train:
    command: action_recognition train -e {config_path}
    config_format: yaml
    inputs:
      dataset.train_dataset_dir:
        type: folder
      dataset.val_dataset_dir:
        type: folder
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  evaluate:
    command: action_recognition evaluate -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  export:
    command: action_recognition export -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  inference:
    command: action_recognition inference -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
data_sources: {}
spec_params: {}
key_defaults: {}
spec_shorthand_keys:
  num_epochs: train.num_epochs
  batch_size: dataset.batch_size
  learning_rate: train.optim.lr
description: Action recognition from video sequences. Supports RGB, optical flow, and joint (multi-stream) input types for
  classifying temporal actions in video clips.
