name: tao-train-segformer
network_arch: segformer
automl_enabled: true
container_image: tao_toolkit.pyt
data_format: unet
gpu_spec_key: train.num_gpus
actions:
  train:
    command: segformer train -e {config_path}
    config_format: yaml
    inputs:
      dataset.segment.root_dir:
        type: folder
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  quantize:
    command: segformer quantize -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  evaluate:
    command: segformer evaluate -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  export:
    command: segformer export -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  inference:
    command: segformer inference -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
  gen_trt_engine:
    command: segformer gen_trt_engine -e {config_path}
    config_format: yaml
    inputs: {}
    outputs:
      results_dir:
        type: folder
    upload_excludes:
    - inputs/
data_sources: {}
spec_params: {}
key_defaults: {}
spec_shorthand_keys:
  num_epochs: train.num_epochs
  batch_size: dataset.batch_size
  learning_rate: train.optim.lr
description: SegFormer for semantic segmentation. Lightweight transformer-based architecture with hierarchical feature extraction.
  Efficient for real-time segmentation tasks.
